#!/bin/bash

function wrap(){
	read -p 'Enter string: ' -r STRINGTOWRAP
	STRINGLENGTH=$(echo "$STRINGTOWRAP" | wc -L)
	STRINGLENGTH2=$(echo "$STRINGTOWRAP" | wc -L)
	touch wrap1.txt
	echo -en "┏" #>> wrap1.txt
	while [ $STRINGLENGTH -gt 0 ]; do
		echo -en "━" #>> wrap1.txt
		((STRINGLENGTH -=1))
	done
	echo -e "┓" #>> wrap1.txt
	echo -en "┃" #>> wrap1.txt
	echo -en "$STRINGTOWRAP" #>> wrap1.txt
	echo -e "┃" #>> wrap1.txt
	echo -en "┗" #>> wrap1.txt
	while [ $STRINGLENGTH2 -gt 0 ]; do
		echo -en "━" #>> wrap1.txt
		((STRINGLENGTH2 -=1))
	done
	echo -e "┛" #>> wrap1.txt
	unset STRINGLENGTH STRINGLENGTH2 STRINGTOWRAP
}
#     1	─
#     2	│
#     3	┌
#     4	┐
#     5	└
#     6	┘
#     7	├
#     8	┤
#     9	┬
#    10	┴
#    11	┼
#    12	╴
#    13	╵
#    14	╶
#    15	╷     
#1	
#     2	
#     3	

function __wrap(){
	WRAP_TB='━'
	WRAP_LR='┃'
	WRAP_TL='┏'
	WRAP_TR='┓'
	WRAP_BL='┗'
	WRAP_BR='┛'
	read -p 'Enter string to wrap: ' -r STRING_W
	STRING_LENGTH=`echo -en '$STRING_W' | wc -L`
	W_LID=$(printf "$WRAP_TL"; printf '━%.s' $(seq 1 $STRING_LENGTH); printf "$WRAP_TR\n")
	W_STRING=$(printf "$WRAP_LR"; printf '$STRING_W'; printf "$WRAP_LR\n")
	W_BOT=$(printf "$WRAP_BL"; printf '━%.s' $(seq 1 $STRING_LENGTH); printf "$WRAP_BR\n")
#     4	
	echo -en "$W_LID\n$W_STRING\n$W_BOT"
	unset WRAP_TB WRAP_LR WRAP_TL WRAP_TR WRAP_BL WRAP_BR STRING_LENGTH W_LID W_STRING W_BOT
}

#     5	
#     6	
#     7	┣
#     8	┫
#     9	┳
#    10	┻
#    11	╋